stages:
  - lint
  - test
  - build
  - scan
  - publish
  - manifest-scan

build-job:
  stage: build
  script:
    - echo "Building the code..."
    - echo "Build completed."

lint-go:
  stage: lint
  script:
    - echo "Linting the code..."
    - echo "Linting completed. No issues found."

test-integration:
  stage: test
  script:
    - echo "Running integration tests..."
    - echo "Integration tests passed SUCCESSFULLY"

test-unit:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Unit tests passed SUCCESSFULLY"

scan:
  stage: scan
  script:
    - echo "Scanning image..."
    - echo "Image scanned SUCCESSFULLY"

publish:
  stage: publish
  script:
    - echo "Publishing image..."
    - echo "Image published SUCCESSFULLY"

manifest-scan-opa:
  stage: manifest-scan
  image:
    name: registry.gitlab.com/asankov/cloud-native-security:opa
  script:
    - cd 02-distribute/manifest-scanning
    - opa eval -i deploy.yaml -d policy.rego 'data.noprivileged.violations[_].msg' --fail-defined


manifest-scan-carbon-black:
  stage: manifest-scan
  image:
    name: registry.gitlab.com/asankov/cloud-native-security:cbctl
  script:
    - cd 02-distribute/manifest-scanning
    - cbctl k8s-object validate -f deploy.yaml --org-key $CBCTL_ORG_KEY --build-step gitlab
      --cb-api-id $CBCTL_API_ID --cb-api-key $CBCTL_API_KEY --saas-url $CBCTL_URL
