apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-signed-image
  namespace: my-secure-ns
spec:
  selector:
    matchLabels:
      app: non-signed-image
  template:
    metadata:
      labels:
        app: non-signed-image
    spec:
      containers:
      - name: non-signed-image
        image: registry.gitlab.com/asankov/cloud-native-security:non-signed
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
